### ISSUE TITLE
Crash on Key

### ISSUE THREAD

**Issue by cwfitzgerald** [livioribeiro/cargo-readme#36]
# Information

cargo-readme version:
`cargo-readme v3.1.2`

rust version:
`rustc 1.38.0-nightly (83e4eed16 2019-07-14)`

# Prior Art

No related issues found.

# Issue

When I run `cargo-readme` against both the main crate and the subcrate in my [project](https://github.com/cwfitzgerald/sarcasm-rs/tree/cc71e20d665dafa15b33b270e6c5a832f3abad47) `cargo-readme` panics complaining:

```
thread 'main' panicked at 'no entry found for key', src/libcore/option.rs:1036:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

If I remove `badges.is-it-maintained-open-issues` and `badges.is-it-maintained-issue-resolution` from the Cargo.toml it correctly outputs the readme file. This would suggest that these keys are things cargo-readme needs to be aware of.

# Backtrace
```
thread 'main' panicked at 'no entry found for key', src/libcore/option.rs:1036:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::option::expect_failed
             at src/libcore/option.rs:1036
   9: cargo_readme::config::badges::is_it_maintained_issue_resolution
  10: <core::iter::adapters::FilterMap<I,F> as core::iter::traits::iterator::Iterator>::next
  11: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  12: cargo_readme::config::manifest::get_manifest
  13: cargo_readme::helper::get_source
  14: cargo_readme::main
  15: std::rt::lang_start::{{closure}}
  16: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  17: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:85
  18: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:394
             at src/libstd/rt.rs:48
  19: main
  20: __libc_start_main
  21: _start
```

**Comment by livioribeiro** [comment]
cargo-readme is aware of these two badges, I will take a look at this as soon as I can
